name: Setup Environment Variables

on:
  push:
    branches:
      - main  # Adjust as per your branch name

jobs:
  setup_environment:
    runs-on: ubuntu-latest  # This refers to the GitHub-hosted runner, not your local machine

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment variables
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
